#!/usr/bin/env python3
import sys
import subprocess

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("No arguments were provided but they are needed", file=sys.stderr)
        exit(1)
    full_args = sys.argv[1:]

    if len(full_args) % 2 != 0:
        print(f"can't parse args: {full_args}", file=sys.stderr)

    cmd = ["ntripclient"]
    arg_p = 0

    while (arg_p + 1) < len(full_args):
        arg_name = full_args[arg_p]
        arg_val = full_args[arg_p + 1]

        if(len(arg_val) != 0):
            cmd.append(arg_name)
            cmd.append(arg_val)

        arg_p += 2

    subprocess.run(cmd, stdout=sys.stderr, stderr=sys.stderr)
